### ISSUE TITLE
Osan 1 tehtävässä Minuutit vuodessa virhe

### ISSUE THREAD

**Issue by jokkeiii** [rage/ohjelmointi-21#11]
Osan 1 tehtävässä Minuutit vuodessa selostuksessa virhe. Mallivastauksessa halutaan kaikki vain yhdelle riville, mutta selostuksessa ohjataan seuraamaan edellisen esimerkin tapaa. Eli esimerkissä laitettu näin:

print("Tuntien määrä vuodessa:")
print(365*24) # 365 päivää, 24 h / pv

mutta mallivastauksessa tuloste halutaan näin:

print("Minuuttien määrä vuodessa:", 365*24*60)

**Comment by pllk** [comment]
Kiitos tämän ongelman tuomisesta tietoomme. Testiä on nyt korjattu niin, että se hyväksyy myös kahden rivin tulostuksen.
