### ISSUE TITLE
Osa 4, tehtävä 7 (alkioiden_arvojen_muutokset): Ei tarkisteta onko validi indeksi arvo.

### ISSUE THREAD

**Issue by Kaxathros** [rage/ohjelmointi-21#18]
Malliratkaisu ei toteuta indeksin tarkistusta, mikäli tämä on validi. Esim. syöte (100, 0) tuottaa index out of range virheen.

if 0 <= index < len(arr):
  arr[index] = val

Tämä on ehkä tarkoituksenmukaisesti toteutettu näin.  (https://tmc.mooc.fi/exercises/115367/solution)

**Comment by pllk** [comment]
Nyt malliratkaisussa on tarkastus tästä
