### ISSUE TITLE
Osa 3 tehtävä 15. hyväksyy virheellisen ohjelman

### ISSUE THREAD

**Issue by lmalmstrom** [rage/ohjelmointi-21#28]
Hei,

Osan 3 tehtävä 15. hyväksyy ohjelman vaikka löydetyt osajonot menisivät päällekäin vastoin tehtävänannon esimerkkiä.
Mikäli syötän ohjelmaani merkkijonoksi: aaaa ja osajonoksi: aa, ilmoittaa ohjelma toisen osajonon sijainniksi 1 vaikka oikea vastaus on 2.

**Comment by pllk** [comment]
Kiitos ilmoituksesta, nyt testauksen pitäisi olla kattavampi
