### ISSUE TITLE
Ongelma 1.osa tehtävä keittoa vai ei palautuksessa

### ISSUE THREAD

**Issue by jannekarkkainen** [rage/ohjelmointi-21#32]
![image](https://user-images.githubusercontent.com/82362021/114347778-2c7c8d00-9b6e-11eb-8e1c-ea5fb66a4792.png)

Ohjelmointi 2021 1.osassa tehtävä keittoa vai ei, päätyy kuvan mukaiseen virheilmoitukseen palautettaessa: FAIL: KeittoaTest: test_1_kramer_1

Tiedostoa src.keittoa_vai_ei ei löytynyt.

Tehtävän pitäisi olla oikein, ainakin se toimii kuten on speksattu.

**Comment by pllk** [comment]
Tuleeko tämä virheilmoitus vielä? En pystynyt toistamaan ongelmaa itselläni.

**Comment by jannekarkkainen** [comment]
> 
> 
> Tuleeko tämä virheilmoitus vielä? En pystynyt toistamaan ongelmaa itselläni.

Asia on kunnossa, tuo virhe tuuttasi esiin myös muiden palautusten kohdalla mutta poistui seuraavana päivänä.
