### ISSUE TITLE
Ongelma itseisarvo tehtävässä

### ISSUE THREAD

**Issue by BlackMorphine** [rage/ohjelmointi-21#33]
![ongelma](https://user-images.githubusercontent.com/42510680/114352617-bfb8c100-9b74-11eb-941b-27c8d7297673.png)

Mikä mahtaa mättää tässä?

**Comment by pllk** [comment]
Tuleeko tämä virheilmoitus vielä? En pystynyt toistamaan ongelmaa itselläni.

**Comment by BlackMorphine** [comment]
Ei tule, siinä oli jokin virhe ja kokeilin myöhemmin uudestaan ni toimii tolla.
kiitos.

**Comment by BlackMorphine** [comment]
Ei tule enää, toimii.
kiitos

2021年4月18日(日) 23:31 Antti Laaksonen ***@***.***>:
