### ISSUE TITLE
osa12-04_kiipeilyreitti virhe malliratkaisussa

### ISSUE THREAD

**Issue by samuelsaari** [rage/ohjelmointi-21#34]
[Malliratkaisussa](https://tmc.mooc.fi/exercises/115521/solution) eikä oletettavasti testeissä ei ratoja laiteta oikein vaikeisjärjestyksen mukaan. Tämän korjaaminen tekee tehtävästä suht vaikean, mutta joka tapauksessa olisi hyvä korjata tai poistaa +/- käyttö tehtävästä sen yksinkertaistamiseksi.

esim. jos s
```
    r1 = Kiipeilyreitti("Kantti", 38, "6A-")
    r4 = Kiipeilyreitti("Pieniä askelia", 12, "6A+")

    reitit = [r1, r4]
    for reitti in vaikeuden_mukaan(reitit):
        print(reitti)
```

Niin vastaus on:
```
Kantti, pituus 38 metriä, grade 6A-
Pieniä askelia, pituus 12 metriä, grade 6A+
```

Eli tämän mukaan 6A- olisi vaikeampi kuin 6A+, mikä ei pidä paikkaansa.

Tämä johtuu siitä, että 

```
print(sorted('+-'))
> ['+', '-']
```

Itse ratkaisin tuon hyvin kökösti (ks. apufunktio vaikeus_mjno), joten olisi kiva nähdä päivitetyistä malleista , miten tuon saisi tehtyä tehokkkasti.
https://tmc.mooc.fi/paste/vJBhpO5DM6zOPBe2GT03Ag

**Comment by pllk** [comment]
Onko jossain esimerkki, jossa on käytetty -? Pitäisi olla vain + tai ei mitään.

**Comment by samuelsaari** [comment]
Eiku totta, ei taida olla miinuksia!

https://www.guidedolomiti.com/en/rock-climbing-grades/
