### ISSUE TITLE
tehtävä huomisen vaatteet (osa 1)

### ISSUE THREAD

**Issue by BlackMorphine** [rage/ohjelmointi-21#37]
Mikä tuossa koodissa mättää?

valittaa seuraavaa:

FAIL: PythonEditorTest: test_10

Syötteellä:
10, ei
ohjelman pitäisi tulostaa rivi
Pue housut ja t-paita
ohjelmasi tulostaa
Kerro huominen sääennuste: 
Pue päälle takki

mutta vaatii eri tekstiä jos vaihdan sitä.

print("Kerro huominen sääennuste: ")
lampotila = int (input("Lämpötila: "))
sataako = (input("Sataako (kyllä/ei): "))

if lampotila >= 20:
    print("Pue housut ja t-paita")

if lampotila > 10:
    print("Pue housut ja t-paita")
    print("Ota myös pitkähihainen paita")

if lampotila == 10:
    print("Pue päälle takki")

if lampotila <= 9:
    print("Pue housut ja t-paita")
    print("Ota myös pitkähihainen paita")
    print("Pue päälle takki")

if lampotila < 5:
    print ("Suosittelen lämmintä takkia")
    print("Pue päälle takki")
    print("Kannattaa ottaa myös hanskat")

if sataako == "kyllä":
    print("Muista sateenvarjo!")

**Comment by karprog1** [comment]
Hei! On oikein, että tulostuksena tulee "Pue päälle takki". Syy ettei "Pue housut ja t-paita" tulostu on se, että koodissasi on seuraava teksti

> if lampotila == 10:
> print("Pue päälle takki")

Edellämainitun ehtolauseen vuoksi vain "Pue päälle takki" tulostuu. 
Kokeile vaihtaa rivi tällaiseksi, eli yhdistä se koodissasi alempana olevan rivin kanssa:

> if lampotila <= 10:
> print("Pue housut ja t-paita")
> print("Ota myös pitkähihainen paita")
> print("Pue päälle takki")

Huomioi myös ehtolauseessa lämptilan ollessa 5, että sinulla on oikeassa järjestyksessä tulostettavat lauseet. Myös kirjoittaessasi "int", tulee sulku auki -merkki suoraan kiinni t-kirjaimeen.

**Lisäksi**
Harjoituksen voi suorittaa myös alla olevan kaltaisella koodilla:

> print("Kerro huominen sääennuste:")
> lampo = int(input("Lämpötila: "))
> sade = input("Sataako (kyllä/ei): ")
> print("Pue housut ja t-paita")
> if(lampo<=20):
>     print("Ota myös pitkähihainen paita")
> if(lampo<=10):
>     print("Pue päälle takki")
> if(lampo<=5):
>     print("Suosittelen lämmintä takkia")
>     print("Kannattaa ottaa myös hanskat")
> if sade == "kyllä":
>     print("Muista sateenvarjo!")

**Comment by BlackMorphine** [comment]
kiitos, mut sain tehtyä jo aikaisemmin tämän
