### ISSUE TITLE
Osa 1 Kertauskysely virhe "Cannot read property 'correct' of undefined"

### ISSUE THREAD

**Issue by MarjaP** [rage/ohjelmointi-21#54]
"Osan 1 kertauskyselyn suorittamisesta seuraa virhe. 

Virheilmoituksen mukaan 
"TypeError: Cannot read property 'correct' of undefined
at ks (https://ohjelmointi-21.mooc.fi/5c90745c52677d2b7909323d086ca518b9bc7e92-b2167550d15b1eece0ba.js:2:803346) ... 
at https://ohjelmointi-21.mooc.fi/framework-5376661c4604f30dbcee.js:2:45881
    at t.unstable_runWithPriority (https://ohjelmointi-21.mooc.fi/framework-5376661c4604f30dbcee.js:2:129150)"
    
Virhe ilmeni, kun olin suorittanut Osan 1 aiemmat osiot ja vastasin kertauskyselyyn (vastaukset olivat oikein). Kertauskyselystä ei tullut hyväksytty-tuulosta vaan näkyviin tuli virheilmoitus. Virheilmoitus ei ole poistunut enkä myöskään pysty tekemään kertauskyselyä uudestaan, kertauskysely on nalkissa.  Osio on ongelman takia kesken. 

Ilmeni PC:ssä, selain Microsoft Edge, näkyy myös, jos kirjautuu omalle MOOC-tilille Google Chromessa. Sammuttaminenkaan ei auta.

Lisäys: sama virhekoodi tulee näkyviin myös seuraavan osion kertauskyselyssä.

Kuva virheilmoituksesta liitteenä. <img width="427" alt="Screenshot_error" src="https://user-images.githubusercontent.com/10886141/117253281-ba872300-ae4f-11eb-965d-5e3aa6a5b688.png">

**Comment by karprog1** [comment]
Näitä ilmaantuu myös muille. Tullut vastaan omissa harjoituksissanikin. Kannattaa jatkaa harjoituksia kunnes tämä on saatu korjattua.
