### ISSUE TITLE
Kertaustehtävät osa 2.3 TypeError: Cannot read property 'correct' of undefined

### ISSUE THREAD

**Issue by Lnyka** [rage/ohjelmointi-21#56]
Näyttäisi tulevan nyt useammassa kertaustehtävässä tämä sama, kun lähettää vastaukset. 
Selaimena chrome.

**Comment by MarjaP** [comment]
Niin tulee. Eikä auta tietokoneen käynnistys & ohjelmapäivitysten tsekkaus eikä tietokoneen tai selaimen vaihto, ei mikään. Kaikki nämä valitse painamalle jne tehtävät vievät  virheilmoitukseen ja siitä virheilmoituksesta ei pääse eroon.

**Comment by karprog1** [comment]
Tulee useilla käyttäjillä. Olen saanut saman virheilmoituksen teidän lisäksi.
