### ISSUE TITLE
Kertaus - osa 2.1

### ISSUE THREAD

**Issue by heikkimat** [rage/ohjelmointi-21#7]
Tehtävä Kertaus - osa 2.1:
Mielestäni 
if luku == false:
on syntaksin mukainen. Ainakin python tulkki sen hyväksyy.

`luku = 3

false = 3

if luku == false:

    print("Toimii")`

**Comment by pllk** [comment]
Tarkoitettu tulkinta on että false on väärin kirjoitettu False, mutta olet myös oikeassa ja tuo tehtävä on moniselitteinen
