### ISSUE TITLE
Toisen asteen yhtälön ratkaisussa häikkää jos sekä a, b että c ovat positiivisia

### ISSUE THREAD

**Issue by AnneKarhes** [rage/ohjelmointi-21#83]
Toisen asteen yhtälön ratkaisussa on mielestäni virhe myös mallivastauksessa jos kaikki annetut luvut ovat positiivisia kokonaislukuja. Ohjelma ilmoittaa virheestä "math domain" https://tmc.mooc.fi/paste/Isfu81XSLVzB6PkNtcAUxg
Tuossa suorituksessa oma versioni on samassa koodissa mutta erotettu #-merkeillä, ettei niitä sotketa mallivastauksen riveihin mukaan.
Tosin siitä, kun olen viimeksi tarkastellut toisen asteen yhtälöitä niin on niiiiiiiiiiiiiiiiiiin kauan aikaa, että sääntöjä on saattanut unohtua, mutta koska mallivastauskin antaa virheen niin olisi kiva jos se tarkastettaisiin. Olisi erittäin kivaa kuulla oliko oikeassa vai väärässä?

**Comment by pllk** [comment]
Toisen asteen yhtälöllä ei ole aina ratkaisua, esim jos a=1, b=1 ja c=1, niin on mahdotonta löytää reaalilukua x niin, että tulos olisi 0. Tehtävässä saa olettaa, että a, b ja c on annettu niin, että on kaksi ratkaisua. Sekä malliratkaisu että oma ratkaisusi toimivat siis tehtävässä halutulla tavalla.
